import { ModelItem } from '../types/model';

const baseUrl = (typeof import.meta !== 'undefined' && import.meta.env?.BASE_URL) || '/';
const cleanBase = baseUrl.endsWith('/') ? baseUrl : `${baseUrl}/`;

/**
 * Built-in real GLB models extracted from the provided aircraft archives.
 * Replaces synthetic/procedural placeholder models with real aerospace 3D assets.
 */
export const DEFAULT_AIRCRAFT_MODELS: ModelItem[] = [
  {
    id: 'mig-23_ub',
    name: 'MiG-23 UB Fighter Jet',
    fileName: 'mig-23_ub.glb',
    size: 15143016,
    fileUrl: `${cleanBase}models/mig-23_ub.glb`,
    createdAt: 1720000000000,
    isDefault: true,
    isSample: false,
    tags: ['Fighter', 'Supersonic', 'Combat'],
    metrics: {
      triangles: 0,
      vertices: 0,
      meshes: 0,
      materials: 0,
      textures: 0,
      animations: 0,
      dimensions: { x: 0, y: 0, z: 0 },
      animationNames: [],
    },
  },
  {
    id: 'f35_fighter_jet',
    name: 'F-35 Lightning II Stealth Jet',
    fileName: 'f35_fighter_jet.glb',
    size: 94280032,
    fileUrl: `${cleanBase}models/f35_fighter_jet.glb`,
    createdAt: 1720000001000,
    isDefault: true,
    isSample: false,
    tags: ['5th Gen', 'Stealth', 'USAF'],
    metrics: {
      triangles: 0,
      vertices: 0,
      meshes: 0,
      materials: 0,
      textures: 0,
      animations: 0,
      dimensions: { x: 0, y: 0, z: 0 },
      animationNames: [],
    },
  },
  {
    id: 'sr72_darkstar',
    name: 'SR-72 Darkstar Hypersonic Jet',
    fileName: 'lockheed_martin_sr72_darkstar__topgun_maverick.glb',
    size: 1038488,
    fileUrl: `${cleanBase}models/lockheed_martin_sr72_darkstar__topgun_maverick.glb`,
    createdAt: 1720000002000,
    isDefault: true,
    isSample: false,
    tags: ['Hypersonic', 'Mach 6+', 'Experimental'],
    metrics: {
      triangles: 0,
      vertices: 0,
      meshes: 0,
      materials: 0,
      textures: 0,
      animations: 0,
      dimensions: { x: 0, y: 0, z: 0 },
      animationNames: [],
    },
  },
  {
    id: 'boeing_787',
    name: 'Boeing 787 Dreamliner',
    fileName: 'boeing_787_dreamliner.glb',
    size: 1031072,
    fileUrl: `${cleanBase}models/boeing_787_dreamliner.glb`,
    createdAt: 1720000003000,
    isDefault: true,
    isSample: false,
    tags: ['Commercial', 'Airliner', 'Twin-Aisle'],
    metrics: {
      triangles: 0,
      vertices: 0,
      meshes: 0,
      materials: 0,
      textures: 0,
      animations: 0,
      dimensions: { x: 0, y: 0, z: 0 },
      animationNames: [],
    },
  },
  {
    id: 'c130_hercules',
    name: 'Lockheed C-130 Hercules',
    fileName: 'lockheed_c-130_hercules.glb',
    size: 5223400,
    fileUrl: `${cleanBase}models/lockheed_c-130_hercules.glb`,
    createdAt: 1720000004000,
    isDefault: true,
    isSample: false,
    tags: ['Transport', 'Tactical', 'Turboprop'],
    metrics: {
      triangles: 0,
      vertices: 0,
      meshes: 0,
      materials: 0,
      textures: 0,
      animations: 0,
      dimensions: { x: 0, y: 0, z: 0 },
      animationNames: [],
    },
  },
  {
    id: 'f104_starfighter',
    name: 'F-104 Starfighter Interceptor',
    fileName: 'f-104_starfighter.glb',
    size: 13325268,
    fileUrl: `${cleanBase}models/f-104_starfighter.glb`,
    createdAt: 1720000005000,
    isDefault: true,
    isSample: false,
    tags: ['Interceptor', 'Classic', 'High-Speed'],
    metrics: {
      triangles: 0,
      vertices: 0,
      meshes: 0,
      materials: 0,
      textures: 0,
      animations: 0,
      dimensions: { x: 0, y: 0, z: 0 },
      animationNames: [],
    },
  },
  {
    id: 'av8b_harrier',
    name: 'AV-8B Harrier II V/STOL Jet',
    fileName: 'av-8b_harrier_ii_usa.glb',
    size: 2676244,
    fileUrl: `${cleanBase}models/av-8b_harrier_ii_usa.glb`,
    createdAt: 1720000006000,
    isDefault: true,
    isSample: false,
    tags: ['VTOL', 'Ground Attack', 'Marines'],
    metrics: {
      triangles: 0,
      vertices: 0,
      meshes: 0,
      materials: 0,
      textures: 0,
      animations: 0,
      dimensions: { x: 0, y: 0, z: 0 },
      animationNames: [],
    },
  },
  {
    id: 'f4ej_phantom',
    name: 'F-4EJ Phantom II Jet',
    fileName: 'f-4ej_japan.glb',
    size: 1778300,
    fileUrl: `${cleanBase}models/f-4ej_japan.glb`,
    createdAt: 1720000007000,
    isDefault: true,
    isSample: false,
    tags: ['Twin-Engine', 'All-Weather', 'Interceptor'],
    metrics: {
      triangles: 0,
      vertices: 0,
      meshes: 0,
      materials: 0,
      textures: 0,
      animations: 0,
      dimensions: { x: 0, y: 0, z: 0 },
      animationNames: [],
    },
  },
  {
    id: 'f86f_sabre',
    name: 'F-86F Sabre Jet',
    fileName: 'f-86f_kyoko_japan.glb',
    size: 1952716,
    fileUrl: `${cleanBase}models/f-86f_kyoko_japan.glb`,
    createdAt: 1720000008000,
    isDefault: true,
    isSample: false,
    tags: ['Transonic', 'Fighter', 'Classic'],
    metrics: {
      triangles: 0,
      vertices: 0,
      meshes: 0,
      materials: 0,
      textures: 0,
      animations: 0,
      dimensions: { x: 0, y: 0, z: 0 },
      animationNames: [],
    },
  },
  {
    id: 'stylized_ww1_plane',
    name: 'Stylized WW1 Biplane',
    fileName: 'stylized_ww1_plane.glb',
    size: 1474576,
    fileUrl: `${cleanBase}models/stylized_ww1_plane.glb`,
    createdAt: 1720000009000,
    isDefault: true,
    isSample: false,
    tags: ['Vintage', 'Biplane', 'Aviation'],
    metrics: {
      triangles: 0,
      vertices: 0,
      meshes: 0,
      materials: 0,
      textures: 0,
      animations: 0,
      dimensions: { x: 0, y: 0, z: 0 },
      animationNames: [],
    },
  },
];
